name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Current user: $(whoami)"
          cd /home/ants/django || exit
          
          # SSH 호스트 키 추가
          mkdir -p ~/.ssh
          ssh-keyscan -H 192.168.0.158 >> ~/.ssh/known_hosts
          
          git remote set-url origin git@github.com:xotjdchl/django.git  # SSH URL로 변경
          git pull origin main
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
