name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Current user: $(whoami)"
          cd /home/ants/django || exit
          git pull origin main
          systemctl restart gunicorn
          systemctl restart nginx
