name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          echo "Current user: $(whoami)"
          cd /home/ants/django || exit
          # echo "RDS_NAME=${{ secrets.DB_NAME }}" >> .env
          # echo "RDS_USER=${{ secrets.DB_USER }}" >> .env
          # echo "RDS_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          # echo "RDS_HOST=${{ secrets.DB_HOST }}" >> .env
          # echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          # echo "The .env file has been created at: $(pwd)/.env"
          git remote update
          git pull origin main
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
