name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Create .env File
        run: |
          cd /home/ants/django/ants_final || exit
          echo "RDS_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "RDS_USER=${{ secrets.DB_USER }}" >> .env
          echo "RDS_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "RDS_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          # .env 파일이 생성된 경로 출력
          echo "The .env file has been created at: $(pwd)/.env"
          
      - name: Run deployment script
        run: |
          cd /home/ants/django/ants_final || exit
          git pull origin main
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
